### ISSUE TITLE
backquote infix underpowered

### ISSUE THREAD

**Issue by skaller** [felix-lang/felix#100]
If f is a function or procedure with parameter type A * B then

    a `f` b

maps to

    f (a,b)

However, this syntax is underpowered. I think it should be removed, or, it should accept an arbitrary expression so for example

    a `g x` b

maps to

    (g x) (a,b)

**Comment by gbluma** [comment]
The following is now possible.

```
fun g(x:int) (y:int, z:int) => x + (y * z);
println$ 3 `g 1` 3;  // prints 10
```

**Comment by gbluma** [comment]
Syntax has changed from ``` x `op` y ``` to ``` x `(op) y ``` to allow the backtick symbol to be used in other places.

```
fun g(x:int) (y:int, z:int) => x + (y * z);
println$ 3 `(g 1) 3;  // prints 10
```

Closing issue.

**Comment by skaller** [comment]
Used extensively changing assignments to stores.
