### ISSUE TITLE
Symbol lookup in 'inherit' statements

### ISSUE THREAD

**Issue by gbluma** [felix-lang/felix#101]
Supposing we have a library class as follows:

```
class String {
  class Str [T] {
    virtual fun str: T -> string;
  }
  // ...
}
```

and usage in a different class

```
open class List {
  open String;
  // ...
  inherit [T with Str[T]] Str[list[T]];
}
```

It doesn't work. Specifically the line 

```
inherit [T with Str[T]] Str[list[T]];
```

can only locate `Str[list[T]]` if we fully qualify the class name, as follows:

```
inherit [T with String::Str[T]] String::Str[list[T]];
```

So, to venture a guess, I think Felix is probably not doing a recursive lookup of that symbol on inherit statements.

**Comment by gbluma** [comment]
The exception triggered:
```
SIMPLE NAME Str NOT FOUND ERROR
In C:/Users/garrett_b/Documents/Projects/felix/felix/src/packages/lists.fdoc: line 687, cols 27 to 39
686:
687:   inherit [T with Str[T]] Str[list[T]];
                               *************
688:   inherit [T with Eq[T]] Set[list[T],T];

Routine: inner_lookup_name_in_env
```

I'm not sure how the control flow reaches `inner_lookup_name_in_env`, but I traced this much:

 (1) Inherit statements are parsed as `ast_inject_module` (grammar.fdoc)
 
```
  //$ Inject all the public members of a class or module
  //$ into a namespace.
  private namespace_stmt := "inherit" stvarlist squalified_name ";" =># 
    "`(ast_inject_module ,_sr ,_2 ,_3)";
```
 
 (2) `ast_inject_module` is converted to `STMT_inject_module` (flx_sex2flx.ml)
 
```
  | Lst [Id "ast_inject_module"; sr; vs; qn] -> 
    let sr = xsr sr in 
    STMT_inject_module (sr, xvs sr vs, xq sr "ast_inject_module" qn)
```
 
 (3) Desugared into a directive tagged as `DIR_inject_module` (flx_desugar.ml)
 
 ```
  | STMT_inject_module (sr,(vs,aux),name) -> 
    let vs = List.map (fun (n,t)->let i = seq() in n,i,t) vs in
    [Dir (sr,DIR_inject_module ((vs,aux),name))]
 ```
 
  (4) During lookup, `DIR_inject_module` is mentioned here (flx_lookup.ml) and it seems to do some kind of name binding/resolution.
  
```
merge_directives state bsym_table rs env name dirs typeclasses =
  let env = ref env in
  let add table =
   env :=
     match !env with
     | (idx, id, nm, nms,con) :: tail ->
     (idx, id, nm,  table :: nms,con) :: tail
     | [] -> assert false
  in
  let use_map = Hashtbl.create 97 in
  add use_map;

  let add_qn (vs, qn) =
    if List.mem (vs,qn) rs.open_excludes then () else
    begin
      let u = [bind_dir state bsym_table !env rs (vs,qn)] in
      let u = get_includes state bsym_table rs u in
      let tables = List.map (pub_table_dir state bsym_table !env ) u in
      List.iter add tables
    end
  in
  List.iter
  (fun (sr,dir) -> match dir with
  | DIR_inject_module (vs,qn) -> 
    add_qn (vs,qn)
 ```

**Comment by skaller** [comment]
There are indeed special restrictions here, of necessity.
Lookup with open and inherit directives is done in a "bare bones" environment
so explicit qualification may be required.

The reason is mutual recursion of opens, for example, leads to absurdity.
Consider 

```
open X;
open Y;
```

These opens should not depend on each other. If Y is defined in X, you'd think it should work, but remember Felix uses setwise scoping, not linear scoping, so the order of opening is not allowed to matter. So it should work if we open Y first, but then Y isn't found. You could say that this should be considered incoherent because it introduces an ordering dependency, but to check that you'd have to open all opens in EVERY order and makes sure that the results are the same in each case. Which is 2^N attempts where N is the number of opens. Besides which, I don't know how to actually check if all 2^N produce the same result!

So the rule is that the argument of an open directive is looked up in an environment where the top level scope does not contain any opens, i.e. a bare environment.

**Comment by skaller** [comment]
```
and mk_bare_env state bsym_table index =
  let parent, sym = Flx_sym_table.find_with_parent state.sym_table index in
  (index, sym.Flx_sym.id, sym.Flx_sym.privmap, [], TYP_tuple []) ::
  match parent with
  | None -> []
  | Some index -> mk_bare_env state bsym_table index
```
is the key routine. The environment is defined in flx_core/flx_mtypes2.ml

```
type env_t = (
  bid_t *           (** container index *)
  string *                    (** name *)
  Flx_name_map.name_map_t *      (** primary symbol map *)
  Flx_name_map.name_map_t list * (** directives *)
  Flx_ast.typecode_t          (** type constraint *)
) list
```
so you can see a bare environment acts as if there were no directives. Grep in flx_lookup.ml to find all the uses.

**Comment by gbluma** [comment]
Ah. That seems sensible enough. I'll add a bit to the documentation to indicate that the user will have to write out full names on inherit commands.

And the work on package refactoring continues.. :+1:

**Comment by skaller** [comment]
Inherit and open are *directives* not commands. So are "use" and "include". The tell the compiler to do something.

**Comment by gbluma** [comment]
Oops, amateur mistake. 

Adding documentation for 'use' as well. I don't think we need to mention qualified names for 'include' because it doesn't refer to classes.
