### ISSUE TITLE
Environment variables in fdoc paths (Windows bug)

### ISSUE THREAD

**Issue by gbluma** [felix-lang/felix#107]
In src/packages/judy.py (as an example) there is a reference to an environment variable (PWD) previously set in the Appveyor script.

```
@title Judy Arrays
@tangler judy.py = $PWD/buildsystem/judy.py
@tangler unix32_judy.fpc = $PWD/src/config/unix/unix32/judy.fpc
@tangler unix64_judy.fpc = $PWD/src/config/unix/unix64/judy.fpc
@tangler win32_judy.fpc  = $PWD/src/config/win32/judy.fpc
```

This appears to work correctly in *nix variants, but Windows actually creates a directory called "$PWD". This subsequently causes some issue with builds (from scratch) unless the contents of this folder are copied into the right locations.

The problem is that the interpretation of the environment variable is left to the OS.

The solution could be to detect the syntax ( "$" identifier) and do an in-process lookup on the path before writing the file.

**Comment by skaller** [comment]
src/tools/flx_iscr.py does check. src/tools/flx_iscr.flx does not.     
```   
if filename[0] == '$':
            join = False
        filename = string.Template(filename).safe_substitute(os.environ)
```

So the bootstrap should work, it uses the Python version. But other commands in the GNUmakefile and Makefile use the executable (Felix) version.

**Comment by gbluma** [comment]
Upon further investigation, I WAS having problems with the python script, but it was related to the environment. 

Apparently setting a variable in powershell doesn't propagate to child processes like nmake. So, I added a bit to the nmake Makefile. This makes it a little more foolproof. I suspect we can then stop setting the variable from the Appveyor script.

Anyway, the FLX version should be more robust now.
