### ISSUE TITLE
[OT] [felix-lang.org] http://felix-lang.org/$//proc/self/cwd//etc/passwd

### ISSUE THREAD

**Issue by AlexanderKurtz** [felix-lang/felix#108]
Hi!

Since I didn't find an administrative contact on your website, I'm reporting this here:

<http://felix-lang.org/$//proc/self/cwd//etc/passwd>

This probably should be fixed.

Best regards

Alexander Kurtz

**Comment by skaller** [comment]
> On 17 Oct. 2017, at 20:36, AlexanderKurtz <notifications@github.com> wrote:
> 
> Hi!
> 
> Since I didn't find an administrative contact on your website, I'm reporting this here:
> 
> http://felix-lang.org/$//proc/self/cwd//etc/passwd
> 
> This probably should be fixed.

Why? It just names the users.

The webserver allows read only access to the whole machine.
It was designed for programmers to view Felix programs.

Google has fun, trolling through the whole of Linux OS :-)

—
john skaller
skaller@users.sourceforge.net
http://felix-lang.org

**Comment by AlexanderKurtz** [comment]
Hey, it's your machine. I just thought I'd let you know.
