### ISSUE TITLE
list syntax

### ISSUE THREAD

**Issue by skaller** [felix-lang/felix#109]
This
```
   var STDIMPORTS=(["plat/flx.flxh", "concordance/concordance.flxh"]);
```
gives the wrong type in my branch, it gives 
```
list[string^2]
```

However this works:
```
    var STDIMPORTS  = Cons ("plat/flx.flxh", Cons ( "concordance/concordance.flxh", Empty[string]));
```
and gives
```
list[string]
```
as expected. On other hand this
```
([1,2,3])
```
seems to work correctly. The code with the two strings built correctly on the main branch. That assignment is part of a special form which constructs a record whose type is put in a typedef using a  ```typeof(expr)``` type, which may not compile correctly in my new code which constructs typedefs in two stages: first by building them as nominal types, and then expanding them to remove references to these nominal types resulting in a purely structural type. Expression evaluation may work correctly during the nominalisation phase because it may in turn depend on typedefs under construction. Its not clear. Care is taken to ensure nominal types don't escape the typedef construction process, however in the presence of a typeof it is possible an incorrect type is constructed. Still it seems suspicious.

**Comment by gbluma** [comment]
I can't reproduce this on your branch. The following works for me without any complaints.
```
var STDIMPORTS : list[string] =(["plat/flx.flxh", "concordance/concordance.flxh"]);
println$ STDIMPORTS;
```

**Comment by skaller** [comment]
Yeah, try building Felix with that in src/package/flx.fdoc. What happens then is that the anonymous struct (record) containing it is the subject of a typedef to a typeof() operator and THAT gets the type wrong. But it works for Cons/Cons/Empty.  Ok, so it looks like a bug in my new typedef handling. 

The problem is there's no recursion or anything fancy involved, and it does work when the type is set by Cons/Cons/Empty. And the bad type would be accounted for is it thought it was a singleton list of a pair. 

The only way this could happen is if it didn't recognise that the argument as an array of two elements, in which case it is an array of one element which is a pair. 

I think this IS possible. If you build Felix now with the latest master (the branch is done with) you will see some Client Errors. These happen during the typedef binding, when typedefs are nominal types. In that case, lookup fails temporarily, but then when we switch to structural typing and do it again it works. So the problem I suspect is that in this one case, the lookup succeeded incorrectly instead of failing.

Yeah. Ok. That explains it. The thing is, lookup is used to bind symbols, so it is a mapping from the unbound symbol table to the bound symbol table and should not depend on the bound symbol table. (My typedef hack changes that slightly).

But the thing is, when overloading functions, the signatures being searched for are bound types. The theory is that bound types can be calculated without the symbol table because the bound form of a nominal type is independent of the symbol table. And we calculate the types first anyhow before the functions.

But there's one exception .. typeof. Which is being used in this case. In that case to calculate a type you have to actually bind an expression which could require overload resolution. Now, you can say "well don't use typeof" but that won't help because the *compiler* uses it all over the place: 
```
val x = expr;
```
is, literally, defined by the *parser* as
```
val x : typeof (expr) = expr;
```
Ok, so I think there really is an issue but not with the list pattern matching so i'll close this.
