### ISSUE TITLE
Request ability to install to alternative directory

### ISSUE THREAD

**Issue by bbarker** [felix-lang/felix#124]
I'd like to be able to use felix in place, or alternatively, install to a custom location - is there a way to do so?

When trying to run `flx` without installing, I get this message:

```
Grammar include file '/usr/local/lib/felix/felix-2018.09.16/share/lib/grammar/grammar.files' doesn't exist, exiting 
```

**Comment by kirbyfan64** [comment]
https://felix-tools.readthedocs.io/en/latest/installation.html?highlight=FLX_INSTALL_DIR#running-in-place

**Comment by bbarker** [comment]
Oops, I had only looked on the main site and the github README.

**Comment by skaller** [comment]
Those instructions miss that you have to set LD_LIBRARY_PATH (on Linux) or (DYLD_LIBRARY_PATH) on OSX as well as PATH. That would be to $PWD/build/release/host/lib/rtl, so stand-alone executables can find shared libraries, including plugins. On Windows, you have to add this directory to the PATH.

If you run via "flx" command it sets the library path for you. But if you make an executable which you want to run directly without "flx", you may need the path if it loads plugins.
