### ISSUE TITLE
Detecting SDL during felix build

### ISSUE THREAD

**Issue by bbarker** [felix-lang/felix#125]
So far, when trying to build, I get a message that sdl-config can't be detected. It is true that in my environment I have only `sdl2-config`, but I noticed that SDL2 is in fact what is desired. I tried creating an alias in bash for sdl-config, and not surprisingly, that didn't work. I also created a symbolic link and added the directory with the link to my PATH, and verified that it appeared to work when running it manually. However, the felix build did not pick it up. 

I think this is only important for running tests, so not a critical issue, but I would like to know of possible ways to correct the issue.

**Comment by skaller** [comment]
Too old. Closing.
