### ISSUE TITLE
Function type mismatch

### ISSUE THREAD

**Issue by skaller** [felix-lang/felix#157]
Felix currently translates RO and WO pointers to plain RW pointers in some lowering routine so the back end only has to deal with one kind of pointer.  Normally we hack all pointers to non-const. However, this fails when the type is part of a function signature, which are not forgiving. In particular an expected C type like 

```void (*)(int const*)```

will not match a felix generated type

```void (*)(int *)```

This can be fixed by allowing RO pointers to get through to the back end, and handling stuff there.

**Comment by gchilds** [comment]
Could you cast the function pointer?

**Comment by skaller** [comment]
Yes, I have done that. I'm working on getting Felix callback machinery operating. It needs a cast too.

**Comment by skaller** [comment]
Solution: Based on Felix "kitchen sink(1)" philosophy the answer is to add to the "bag of tricks(2)". 

**Provide both.**

In detail, provide two overloaded callback thunks, one with a signature for Felix use and one for C.

**Comment by skaller** [comment]
The original Issue should be fixed now.
