### ISSUE TITLE
Any editor out there with syntax highlighting for Felix lang?

### ISSUE THREAD

**Issue by 3oheicrw** [felix-lang/felix#170]
And possibly code completion?

**Comment by skaller** [comment]
Vim at least. Look in src/misc

**Comment by jpgpng** [comment]
https://github.com/Alexey-T/CudaText/issues/4381

**Comment by Alexey-T** [comment]
CudaText lexer is ready, it is here yet (donwload zip file and open in CudaText).
it will be in Addons Manager soon.
https://github.com/Alexey-T/CudaText/issues/4381#issuecomment-1257056806
