### ISSUE TITLE
Support OCaml 4.14.0

### ISSUE THREAD

**Issue by tqo50396** [felix-lang/felix#186]
It seems this version is not supported. I hacked the build script to have it working on MinGW (see: #185), but it always failed with:

```
looking for ocamldep.opt.exe            : ok C:\msys64\mingw64\bin/ocamldep.opt.exe
looking for ocamlc.opt.exe              : ok C:\msys64\mingw64\bin/ocamlc.opt.exe
checking ocamlc.opt.exe version         : 4.14.0
checking if ocamlc.opt.exe can make objects: ocamlc.opt.exe compiler failed
make: *** [GNUmakefile:116: configure] Error 1
```

Extracted from `fbuild.log`:

```
looking for ocamldep.opt.exe            : 
ok C:\msys64\mingw64\bin/ocamldep.opt.exe
looking for ocamlc.opt.exe              : 
ok C:\msys64\mingw64\bin/ocamlc.opt.exe
checking ocamlc.opt.exe version         : 
MainThread: starting 'C:\\msys64\\mingw64\\bin/ocamlc.opt.exe -version'
 + C:\msys64\mingw64\bin/ocamlc.opt.exe -version
4.14.0
 - exit 0, 0.00 sec
4.14.0
checking if ocamlc.opt.exe can make objects: 
MainThread: starting 'C:\\msys64\\mingw64\\bin/ocamlc.opt.exe -c -I build/release -w -26 -w -20 -w -21 -o build/release/temp.cmo build/release/temp.ml'
 * ocamlc.opt.exe                       : build/release/temp.ml -> build/release/temp.cmo
 + C:\msys64\mingw64\bin/ocamlc.opt.exe -c -I build/release -w -26 -w -20 -w -21 -o build/release/temp.cmo build/release/temp.ml
File "command line", line 1:

Error: Unbound module Stdlib
 - exit 2, 0.02 sec
ocamlc.opt.exe compiler failed
```

**Comment by skaller** [comment]
SO when I build 4.14 I get this rubbish:
```
build/compilerlibref/pparse.odoc
Warning: Module or module type Pervasives not found
Warning: Element Stdlib.Hashtbl.seeded_hash not found
Warning: Element Stdlib.Map.Make not found
....
```

Like  ... this is the build from 4.14 branch of the GitHub repo. It should have this junk in in.
Nevertheless Felix is building... 

```
~/ocaml>ocamlopt -v
The OCaml native-code compiler, version 4.14.2+dev0-2022-12-19
Standard library directory: /usr/local/lib/ocaml
```

**Comment by tqo50396** [comment]
Maybe something is wrong with the OCaml package provided by MSYS2 (https://packages.msys2.org/package/mingw-w64-x86_64-ocaml). I can't do anything with it!

```
$ ocamlopt -v
The OCaml native-code compiler, version 4.14.0
Standard library directory: /mingw64/lib/ocaml
```

**Comment by skaller** [comment]
But it should work. Do you have any other Ocaml installs that might be creating an issue? Sometimes you have to set an environment variable to tell Ocaml where to find the library. You can also try the bytecode interpreter:

ocaml
> print_endline "Hello world;;

That uses the print_endline function which is in the (bytecode version of) Stdlib.

**Comment by skaller** [comment]
Did you install the libraries? It's a separate package according to MSYS2 docs:

Package: [mingw-w64-x86_64-ocaml-compiler-libs](https://packages.msys2.org/package/mingw-w64-x86_64-ocaml-compiler-libs?repo=mingw64)

**Comment by skaller** [comment]
are u still having problems with ocaml?

**Comment by tqo50396** [comment]
> are u still having problems with ocaml?

Yes. I'm unable to use Felix on Windows. I will try it someday on Linux.

**Comment by skaller** [comment]
Well the problem is with Ocaml not Felix.  Of course there is another solution on Windows: install Ubuntu. The only thing that will not work out of the box are the graphics using SDL2, which requires an X server to be installed.
