### ISSUE TITLE
Syntax highlighting for Felix

### ISSUE THREAD

**Issue by tqo50396** [felix-lang/felix#188]
Which text editors have syntax highlighting support for Felix? Does Felix have a recommended IDE?

**Comment by skaller** [comment]
I support vim. Others have done howl and emacs. You can try C++ at a pinch.  If you know how to write highlights for your editor I can get you a starting list of "keywords".  The main "IDE" is `flx` and perhaps your shell. `flx` autobuilds so there's no need for any IDE tooling for that. The other useful tool is `flx_web` which is a webserver (part of the build) which can show *.flx and *.fdoc (and C/C++) files with hyperlinking (but no editing support).

You really don't need an IDE with Felix. Other languages require a lot of boilerplate. Felix is very high level and most things can be expressed succinctly. My main searching tool is actually `grep`. 

I would like a VScode plugin, but I haven't been able to find a quick way to make one (i.e. that doesn't take months learning what you need to know to get it to work).

**Comment by skaller** [comment]
Just FYI: Felix has a novel thing called DSSLs, Domain Specific Sub-Languages. In a DSSL, you can design your own language, and just add it to Felix. For example in Felix you can write:
```
regdef ident = letter  (letter | digit)*;
```
and the grammar for and semantics of that syntax is part of the regular definition DSSL. That syntax is NOT in the base Felix language. It is is the LIBRARY. Other language allow you to overload operators. Felix allows you add your own grammar (as long as it doesn't conflict with the base language: you can design a domain specific SUB language which is an extension of Felix).

In fact, there is a small WHITE LIE above. There IS NO FELIX LANGUAGE. The WHOLE language is a defined in user space in the standard library. The ONLY hard coded syntax is the syntax of the grammar used to specify the syntax of grammars (i.e. as a bootstrap).

Now why bring this up? How the heck could any of the lame IDE around possibly cope with a self-extending language?
Felix is orders of magnitude too powerful for them. At best you can program an IDE to support a commonly used grammar (the standard grammar). It would be really cool if IDE's could be self-extending, but most require hard coded plugins. 

I'd really like VScode support. I think it's a pretty good system compared to the crap I use: `vim`. But I've been using `vi` family editors for 50 years...  I surely don't recommend it to a newcomer. And I haven't been able to find a "VScode plugin for dummies" example I can just plugin and edit a bit of.

**Comment by tqo50396** [comment]
> I support vim. Others have done howl and emacs. You can try C++ at a pinch. If you know how to write highlights for your editor I can get you a starting list of "keywords".

Please give me the list of keywords. Thank you.

**Comment by tqo50396** [comment]
@skaller What kind of statement is `_`?

`syn keyword felixStatement _`

**Comment by tqo50396** [comment]
Geany syntax highlighting for Felix:

https://github.com/tqo50396/felix.geany.syntaxcoloring

**Comment by skaller** [comment]
You can add to
```
arc/misc/geary/*

**Comment by skaller** [comment]
> On 10 Dec 2023, at 01:33, tqo50396 ***@***.***> wrote:
> 
> 
> @skaller What kind of statement is _?
> 
> syn keyword felixStatement _

It’s not a statement it’s a pattern without a name that matches anything i.e. a wildcard.
It just gets highlighted the same way. Example

match (1,2) with
| (1,_) => println$ “One in pos 0”;
| _ => println$ “No 1 in pos 0:;
endmatch;


—
John Skaller
***@***.***

**Comment by tqo50396** [comment]
> You can add to
> 
> ```
> src/misc/geary/*
> ```

I submitted the PR. I also deleted https://github.com/tqo50396/felix.geany.syntaxcoloring.
