### ISSUE TITLE
flx_world is spaghetti

### ISSUE THREAD

**Issue by rfistman** [felix-lang/felix#58]

**Comment by Immortalin** [comment]
@skaller what does all the free pascal files do?

**Comment by kirbyfan64** [comment]
@Immortalin `.fpc` files are ***F**elix **P*kg-**C**onfig* files. Felix has a tool kind of like `pkg-config` to manage external libraries; these are the config files it uses. The files have nothing to do with Pascal.

**Comment by Immortalin** [comment]
Oops

**Comment by gbluma** [comment]
Is there a reason this ticket is still open?

**Comment by skaller** [comment]
flx_world is probably still spaghetti. This is the technology used to allow Felix to be embedded in C/C++ in particular inside event loops.

**Comment by shayne-fletcher** [comment]
Pasta :)

**Comment by skaller** [comment]
Cleaning up and documenting Embedding is an open topic but this issue is too old.
