### ISSUE TITLE
OCaml 4.02.0 will cause build failures

### ISSUE THREAD

**Issue by shayne-fletcher** [felix-lang/felix#66]
Mutable strings are deprecated in OCaml 4.02. Use `Bytes.t` and `Bytes` functions instead. The reason for the build failures is the build treats level 3 warnings as errors. Quick workaround is to remove the 'D' in the 'FPDSU' flags in fbuildroot.py and src/tools/flx_build_flxg.flx.

**Comment by BigBoneDaddy** [comment]
@shayne-fletcher Good catch nice job

**Comment by skaller** [comment]
Too old. Everything is upgraded I think EXCEPT Dypgen executable. Dypgen library is updated though.
