### ISSUE TITLE
make scoop -- build fail

### ISSUE THREAD

**Issue by gitfoxi** [felix-lang/felix#70]
```
$ make scoop
make: *** No rule to make target `demos/scoop/bin/scoop.flx', needed by `build/release/host/bin/scoop'.  Stop.
```

**Comment by kirbyfan64** [comment]
You can try editing the makefile to instead point to `src/tools/scoop.flx`, but, last time I tried, it didn't build.

**Comment by skaller** [comment]
Yep, it's out of date and the developer is not about. I'm still thinking of how to build a package manager. Some preparatory work has been done by driving the system layout through a control file now.
