### ISSUE TITLE
Build failure on Macosx

### ISSUE THREAD

**Issue by unktomi** [felix-lang/felix#80]
BOOTFLX
# =========================================================
# copying ./src to build/release/share/src
# =========================================================

flx_build_prep --target-dir=build/release --target-bin=trial --source-dir=build/release \
            --source-bin=host --clean-target-bin-dir --copy-compiler --copy-pkg-db \
            --copy-config-headers --toolchain=toolchain_clang_osx --debug
make: flx_build_prep: No such file or directory
make: **\* [prep] Error 1

**Comment by kirbyfan64** [comment]
What if you run `make bootstrap-tools`?

**Comment by unktomi** [comment]
That target works. However, subsequent make gives the same error as above.

**Comment by skaller** [comment]
Sorry you have to run

. buildscript/osxsetup.sh

first to set up the environment variables:

~/felix>cat buildscript/osxsetup.sh
export PATH=build/release/host/bin:$PATH
export DYLD_LIBRARY_PATH=build/release/host/lib/rtl:$DYLD_LIBRARY_PATH
