### ISSUE TITLE
Cannot find dll/shared library toolchain_clang_osx.dylib during make

### ISSUE THREAD

**Issue by fuzzthink** [felix-lang/felix#84]
`sudo make`
Got error below.

OS: OSX 10.9.5
clang: 
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix

Is clang version the problem? Is 3.7 really needed? clang 3.6.0svn is the latest available on latest Mavericks 10.9.5. Really don't want to upgrade beyond Mavericks.

Also, the tarball link is still broken. If it won't be fixed, the instruction for tarball and link should be removed.  

```
...
Compiling ML  src/compiler/flxg/flxg.ml
Linking executable build/flxg-tmp/flxg
Done, exe = src/compiler/flxg
cp build/flxg-tmp/flxg build/release/host/bin
# =========================================================
# rebuild rtl
# =========================================================
flx_build_rtl --target-dir=build/release --target-bin=trial
flx_build_rtl v1.7
  build-package = flx_rtl_core
  target-dir    = build/release
  target-bin    = trial
  tmp-dir       = build/rtl-tmp
bootpkg=flx_rtl_core build image=build/release
toolchain    : toolchain_clang_osx
 flx_exceptions       flx_exceptions       src/exceptions
           judy                 judy         src/judy/src
         flx_gc               flx_gc               src/gc
    flx_strutil          flx_strutil          src/strutil
             dl                                          
    flx_dynlink          flx_dynlink          src/dynlink
        pthread                                          
    flx_pthread          flx_pthread          src/pthread
            flx                  rtl              src/rtl
          demux                demux            src/demux
      flx_async            flx_async        src/flx_async
           faio                 faio             src/faio
            re2              flx_re2          src/re2/re2
   flx_rtl_core                                          
Felix exception handler
Dynamic linkage error
filename: toolchain_clang_osx.dylib
operation: LoadLibrary/dlopen
what: Cannot find dll/shared library
make: *** [rtl] Error 253
```

thanks.

**Comment by skaller** [comment]
> On 6 Jul 2016, at 20:26, fuzzthink <notifications@github.com> wrote:
> 
> sudo make
> Got error below.

Yes, sorry, please run

	. buildscript/osxsetup.sh

to set up the DYLD_LIBRARY_PATH and PATH variables.
                
> Felix exception handler
> Dynamic linkage error
> filename: toolchain_clang_osx.dylib
> operation: LoadLibrary/dlopen
> what: Cannot find dll/shared library
> make: *** [rtl] Error 253
> 
> thanks.

—
john skaller
skaller@users.sourceforge.net
http://felix-lang.org

**Comment by skaller** [comment]
> Is clang version the problem? Is 3.7 really needed? clang 3.6.0svn is the latest available on latest Mavericks 10.9.5. Really don’t want to upgrade beyond Mavericks.

You don’t need to, you can get a clang tarball for OSX from clang people.
That’s what I did.

> 
> Also, the tarball link is still broken. If it won’t be fixed, the instruction for tarball and link should be removed.

Noted. Thanks. There is a tarball, its on the GitHub site, but only for
Windows and Linux/gcc.

—
john skaller
skaller@users.sourceforge.net
http://felix-lang.org

**Comment by skaller** [comment]
BTW: I do not know if clang 3.6 is enough or not. C++11 support is required. 
I have Yosemite 10.10.5. Felix is using C++11 atomics and some other thread support stuff, clocks etc. There's also some lightweight use of older features like uniform initialisers and auto.

**Comment by skaller** [comment]
Also as to the website docs: normally the website is updated from a release tarball. Unfortunately Appveyor (Windows) is not working properly. I have changed the download link. But OSX tarball isn't available, we use Appveyor and Travis CI servers to cut the releases.

**Comment by kirbyfan64** [comment]
Doesn't Travis have OSX support?

**Comment by fuzzthink** [comment]
I did run the osxsetup.sh, the problem is if var wasn't set, the colon separator will be added to the var. My PR https://github.com/felix-lang/felix/pull/85 fixed that.

The build was good until the following error.

Re clang: Good to know I don't need to upgrade OS to get upgrade clang. clang 3.6 supports up to c++14, so I think I should be good here.

Re Travis: Ya, if it supports OSX, it will be great to not have users build from source.

```
mkdir -p build/release/tutopt
build/release/host/bin/flx_tangle --indir=build/release/share/src/web/tutopt --outdir=build/release/test/tutopt
Base = .* : 11 files
for file in src/web/tutopt/*.fdoc; do build/release/host/bin/flx_iscr $file build/release/test/tutopt; done
#
# ============================================================
#
# TESTING OPTIONAL COMPONENTS
#
# Tests are expected to fail if the relevant third party
# support is not available or Felix is not properly configured
# to use it.
# ============================================================
#
FLX_INSTALL_DIR=build/release build/release/host/bin/flx --felix=build.fpc --usage=prototype --expect --input --nonstop --indir=build/release/test/tutopt --regex='.*\.flx' build/release/test/tutopt
Processing 9 files
Processing [01/09]: mmap_01.flx
package not found: mmap
[FlxPkg:map_package_requirements] Error 1 executing flx_pkgconfig, args=list('--path+=build/release/host/config', '--path+=/usr/local/lib/felix/packages/host/config', '--field=cflags', '--keepleftmost', '@/Users/john/.felix/cache/text/Users/john/dev/srcs/felix/build/release/test/tutopt/mmap_01.resh')
make: [tutopt-check] Error 1 (ignored)
build/release/host/bin/flx --felix=build.fpc --usage=prototype --expect --nonstop --indir=build/release/test/extras --regex='.*\.flx' build/release/test
Error opening dir
Processing 0 files
Batch result (00 OK + 00 FAIL)/ 0
```

Which dir is it referring to here? ```build/release/test``` is read/writeable by me. It will be helpful to spell out which dir is it referring to.

It says can not find mmap. Which is it supposed to be?

thanks.

**Comment by skaller** [comment]
> On 7 Jul 2016, at 01:27, Ryan Gonzalez <notifications@github.com> wrote:
> 
> Doesn’t Travis have OSX support?

1. They have limited OSX support.

2. If you can figure out how to get the OSX build to happen as well as Linux
you’re a genius.

3. Travis has a time limit, no idea if it applies only to each build
or to all the builds together.

In principle, both Travis an Appveyor can do multiple builds.
In practice, the build “matrices” share some of the rest of the
script, which seems weird to me. A better design would have
just been multiple scripts.

—
john skaller
skaller@users.sourceforge.net
http://felix-lang.org

**Comment by skaller** [comment]
> The build was good until the following error.

Cool! that’s normal, it isn’t an error.

> Error opening dir
> Processing 0 files
> Batch result (00 OK + 00 FAIL)/ 0
> 
> Which dir is it referring to here? build/release/test is read/writeable by me. It will be helpful to spell out which dir is it referring to.
> 
> It says can not find mmap. Which is it supposed to be?

[There are two errors, make ignored one of them and then there
was another]

1. Error opening dir, I think, refers to build/release/test/extras.
Which would have been created had the previous operation
succeeded.

2. There are some optional extras. I never did figure out exactly
how to configure it. SDL2 is another. Support is directly
in Felix. There should be a systematic way to check if 
an extra thingo is installed or not. There isn’t.

3. mmap (or related service) should be standard, its available on 
Windows (by another name) as well. 

There are two parts to this: (a) the primary use is available
on all platforms: mapping a file readonly into memory.
But the filename is platform dependent, so tricky to put
into test code.

The secondary use is only available on some platforms,
namely MMAP_ANONYMOUS. Linux provides that.
OSX doesn’t. Neither does Windows I think but I’m not sure.
It sucks. That function would be really cool.

4. You will occasionally see really weird error messages
relating to the file system.

This is a design fault in Unix. There is no systematic way to assign
or use program exit codes. Felix uses certain codes when exceptions
are trapped. 

Bash thinks they’re something else.

—
john skaller
skaller@users.sourceforge.net
http://felix-lang.org

**Comment by fuzzthink** [comment]
Ok, sounds like these 2 aren't critical errors. Seems like I should run ```make install``` afterwards as running flx fails on locating grammar file. Reasons why it the instruction wasn't clear:

There's no line spacing between that ```make install``` and the Windows instructions so it looks like it's only needed for Windows. Also the ```make install``` runs win32install.bat which assumes "c:\" path. So both the instruction and the actual code make it like it's for Windows only.

I did manually copy the build/release to the 2016.06.29-pelican path and things work now. But how can the build script be wrong? I couldn't have been the first person running it in non-Windows machine.

**Comment by skaller** [comment]
cat GNUmakefile

to see what the install does. You need sudo make install. 

You do NOT actually HAVE to install Felix for it to work. 
You do need PATH and DYLD_LIBRARY_PATH to be set up as required though.

I use this:

    ~/felix>cat ~/.felix/config/felix.fpc
    FLX_INSTALL_DIR: build/release
    FLX_LIB_DIRS: build/release/share/lib build/release/host/lib /usr/local/lib/felix/packages/share/lib
    FLX_CONFIG_DIRS: build/release/host/config /usr/local/lib/felix/packages/host/config

so my flx will look in the latest build instead of the installed Felix (which I keep as a backup in case the bootstrap fails).  So I get:
    ~/felix>which flx
    /usr/local/bin/flx

in a fresh terminal and
    ~/felix>which flx
    build/release/host/bin/flx

after running buildscript/osxsetup.sh.  However this only affects "flx" execution, i.e. where to find "flx" and the run time and plugin dylibs. With the felix.fpc control file, "flx" will tell the flxg compiler, C++ compiler and linker, and run time for programs it runs to look where the control file says, in the repository build directory. So the program flx RUNS will use the dylibs in the build directory, which are not the same ones flx uses unless osxsetup.sh is run. Confusing I know. But it means most of the time I'm working on the bleeding edge, but I have a fallback.

**Comment by skaller** [comment]
Having said that:

    ~>flx
    Grammar include file '/Users/skaller/build/release/share/lib/grammar/grammar.files' doesn't exist, exiting
   ~>cd felix
   ~/felix>flx
    usage: flx [options] filename

This definitely seems to be a bug.

    ~/felix>mv ~/.felix/config/felix.fpc ~/.felix/config/felix.fpcxxx
    ~/felix>flx
    Grammar include file '/usr/local/lib/felix/felix-2016.04.10-rc2/share/lib/grammar/grammar.files' doesn't exist, exiting
    ~/felix>which flx
    /usr/local/bin/flx
    ~/felix>sudo make install
    .... 
    ~/felix>cd ..
    ~>flx
    Cache may be out of date due to grammar upgrade!
    ....

The above repeats every time until i actually build something. But then that works.
So there's something weirdish happening. What's happening is that the grammar include file is a relative filename, which is converted to an absolute filename by bolting on the current directory absolute pathname. If I remove the control file, then it uses the installation default instead. That fails because I didn't run the install.

So this also explains why, without the install, flx doesn't work without osxsetup.sh. I deliberately deleted my installation at one stage to avoid confusion.

The system is design to allow multiple deployment models, from personal computing to enterprise wide installation, and is thus a bit complex. The problem of course is that testing everything fits together is hard to do, and can basically only be done properly by first time users.

**Comment by fuzzthink** [comment]
I see. Didn't see GNUmakefile so was looking at the wrong Makefile. Thank you for explaining and getting deeper into the problem.

**Comment by skaller** [comment]
Windows nmake uses Makefile but GNU make prefers GNUmakefile so it seemed best to use Makefile for Windows and GNUmakefile for unix, otherwise you'd have to do make -f filename or something.

**Comment by skaller** [comment]
I want the whole process to work nicely, especially for newcomers. I'm particularly interested in newcomer opinions, especially regarding the language, because once one is deeply into it its hard to see things from a fresh perspective. [Yes I know the docs suck :]

**Comment by fuzzthink** [comment]
You got to give it some perspective, it's head and showers above what it was 2 years ago ;) . I am actually pretty impressed this time since I had given up on Felix before when both the site and the docs was that bad ^_* .  If I'm still digging the language after a month, I'll try to make the setup doc a little better.

**Comment by skaller** [comment]
Make sure to be on the mailing list (even if you delete all the mail). Just email to

    felix-language@googlegroups.com

If you have any questions ask. Don't bite off too much at once. It takes a while to get the hang of various things including, if not especially, how to search for library functions. The best way is to just ask.

The system is complex but, what first time users see as complex isn't, the complexity is elsewhere in the abstract machine model. The syntax is all user defined and there's a lot of it, because one of the themes of Felix is that users should not just make new library functions, and overload operators, but design new grammar to suit their application domain.

**Comment by skaller** [comment]
closed due to age
