### ISSUE TITLE
Fix the license

### ISSUE THREAD

**Issue by colejohnson66** [felix-lang/felix#86]
The license is similar to the WTFPL, which is actually a pretty bad license. It doesn't cover even the concept of "implied warranty". While I'd advocate for the GPL, anything but a "WTFelixPL" would be better.

**Comment by colejohnson66** [comment]
https://news.ycombinator.com/item?id=6047560

**Comment by gbluma** [comment]
I agree that the license should be improved, but the situation is complicated by a few factors.

1) we bundle some open source libraries with the compiler. If these are GPL, then that could imply a GPL license for all of Felix. For an open source project, that wouldn't be terrible, but for users it could be bad.

2) shipping our run time library GPL could imply all compiled user programs are deemed GPL as well. And this is most definitely bad. LGPL has some barriers to this effect, but it could require the LGPL code to be linked with shared libraries--to maintain binary separation.

3) MIT and BSD licenses are weak in some ways that allow the project to be stolen by influential people. Perhaps that stealing is good for user programs (so users can own their own code) but it could be bad if, for example, Oracle buys Felix and kills the project.

4) we may want to split the project into a few licenses, but that takes some thought and attention. Finding the areas to separate can be tough, and it could require some auditing of code to ensure we don't break out own rules.

One license that is fairly permissible is the Apache license. Not sure about the specifics, but it's good to think about these things though.

--
Garrett

**Comment by skaller** [comment]
> On 11 Jul 2016, at 15:01, Garrett Bluma <notifications@github.com> wrote:
> 
> I agree that the license should be improved, but the situation is complicated by a few factors.

The licence is FFAU. Free For Any Use. You can take the source
and distribute it yourself under any licence you please (noting
only the licences of any included parts).

If there’s a fault, it is probably failing to properly and specifically
mention which parts are from other places and what licences
apply to them. Judy, Dypgen and OCS Scheme, primarily.
Only Judy is needed at run time though. And I may soon dump it.


> One license that is fairly permissible is the Apache license. Not sure about the specifics, but it’s good to think about these things though

Creative Commons Public Domain No Attribution required.

Note that I see no reason to kowtow to US legal system in this area.
At least not at this time.

—
john skaller
skaller@users.sourceforge.net
http://felix-lang.org

**Comment by colejohnson66** [comment]
> 1) we bundle some open source libraries with the compiler. If these are GPL, then that could imply a GPL license for all of Felix. For an open source project, that wouldn't be terrible, but for users it could be bad.
> 
> 2) shipping our run time library GPL could imply all compiled user programs are deemed GPL as well. And this is most definitely bad. LGPL has some barriers to this effect, but it could require the LGPL code to be linked with shared libraries--to maintain binary separation.

GCC gets around this with it's ["linking exception"](https://gcc.gnu.org/onlinedocs/libstdc++/manual/license.html).

**Comment by colejohnson66** [comment]
> If there’s a fault, it is probably failing to properly and specifically
mention which parts are from other places and what licences
apply to them.

No. The fault is that the license is similar to the WTFPL. You don't even cover the most basic concept every open source license should have: **implied warranty**. If I download your program and it breaks my computer, I can actually _sue you_ over that due to warranty laws across the country. If you really want a "do what you want" license, I suggest the Apache license or CC0 (not public domain as that's actually not a well defined legal term).

Your license specifically says "Felix is free for any use." Well, what counts as "use"? Actually what even counts as "Felix"? IANAL, but IIRC, in this case, "Felix" would refer to the compiled binary, not the source code (that would be "Felix's source code"). If Felix isn't the source, then legally speaking, I **can't** use the source code in any way. It's completely proprietary. If "Felix" does include the source, again, what does it mean to "use" it? Does decompiling count as "using" a program? The legal system disagrees.

You may think that a WTFPL-esque license is a great one due to its simplicity and ease of understanding, but by using one, you are actually _denying_ your users of the right to do certain things. There's a reason open source licenses such as Apache, LGPL, CC0, etc. are long. It's the same reason the laws of the land aren't "you can't fly an airplane lower than 1000 feet" or something. What counts as an airplane? Do drones count? Do paper airplanes count? There's all those little nuances people don't think about.

Just as you shouldn't "roll your own crypto" (because there's nuances you might not know about that the crypto "geeks" do), you shouldn't "roll your own license". I'd go as far as saying it should be **considered harmful**. It should be left to a lawyer who knows what he's doing.

**Comment by skaller** [comment]
> 3) MIT and BSD licenses are weak in some ways that allow the project to be stolen by influential people. Perhaps that stealing is good for user programs (so users can own their own code) but it could be bad if, for example, Oracle buys Felix and kills the project.

How is that bad? I could afford to buy batteries for my boat, so I can keep my
computer running!

And it would have no impact on the code anyhow, since it is FFAU licenced.
All copies existing before the purchase would continue to remain 
unencumbered.

The licence (FFAU) specifically allows big companies or small to take
the code and do whatever they like with it. You would only breach
copyright if you copied THEIR copy.

What FFAU means is that we cannot distribute GPL’d software with
the package, or any other software with a restrictive licence.

—
john skaller
skaller@users.sourceforge.net
http://felix-lang.org

**Comment by skaller** [comment]
> On 11 Jul 2016, at 15:54, Cole Johnson <notifications@github.com> wrote:
> 
> If there’s a fault, it is probably failing to properly and specifically
> mention which parts are from other places and what licences
> apply to them.
> 
> No. The fault is that the license is similar to the WTFPL. You don't even cover the most basic concept every open source license should have: implied warranty. If I download your program and it breaks my computer, I can actually sue you over that due to warranty laws across the country.\

You can? WHICH country? I’m not American. Your laws don’t apply here.
Sue away. I have nothing to lose.


—
john skaller
skaller@users.sourceforge.net
http://felix-lang.org

**Comment by skaller** [comment]
> that due to warranty laws across the country. If you really want a “do what you want" license, I suggest the Apache license or CC0 (not public domain as that's actually not a well defined legal term).

It is in EUROPE.

> Just as you shouldn't "roll your own crypto" (because there's nuances you might not know about that the crypto "geeks" do), you shouldn't "roll your own license". I'd go as far as saying it should be considered harmful. It should be left to a lawyer who knows what he’s doing.

From which country? Which laws?

If you have a problem:

(a) clone the repo on GitHub
(b) Apply whatever licence you like to your copy


—
john skaller
skaller@users.sourceforge.net
http://felix-lang.org

**Comment by skaller** [comment]
> LGPL, CC0, etc. are long. It's the same reason the laws of the land aren't "you can't fly an airplane lower than 1000 feet" or something. What counts as an airplane? Do drones count? Do paper airplanes count? There’s all those little nuances people don't think about.

You clearly don’t understand the laws of the country I am a citizen of (like or not).
The laws are PRECISELY what you say: vague. Intentionally. Because here
we use the Westminster system and it is up to courts to interpret the intention
and meaning of legislation. There is a long history such that most of the
law is in fact made by the courts, not by legislature, its called Common Law.
The common law is unwritten, except in judgements made about it by courts.

America, again for better or worse, does not have any common law.

I’m sure China has a different system again. As does, for example,
France and Indonesia where you are guilty until proven innocent.

Anyhow, I’m really interested in discussing the ideas and technology,
not the politico/legal framework surrounding it. (I mean I’m happy
to talk about that too, but not in this forum).

If the project generates enough actual users that have financial
interests to protect, then a licence suiting those users can be arranged
at that time.

—
john skaller
skaller@users.sourceforge.net
http://felix-lang.org

**Comment by kirbyfan64** [comment]
https://creativecommons.org/share-your-work/public-domain/cc0/

**Comment by phase** [comment]
Using an OSS license or CC gives users the comfort of something familiar. I would recommend MIT, but CC might work better.

**Comment by skaller** [comment]
> On 12 Jul 2016, at 01:18, phase <notifications@github.com> wrote:
> 
> Using an OSS license or CC gives users the comfort of something familiar. I would recommend MIT, but CC might work better.

Some of the existing code being used was BSD.

I personally like Creative Commons, however I have heard comment their
licences aren’t really suitable for software.  No one heard of a book breaking
your computer.

However right now FB has just shy of 50 ppl in the Felix group and I doubt
more than 5 people in the world actually have a copy (not counting bots).
I’m more concerned with ppl’s comfort with the language that legal stuff.
After all I’ll be gone soon enough so who is going to sue anyhow?


—
john skaller
skaller@users.sourceforge.net
http://felix-lang.org

**Comment by Immortalin** [comment]
One possible solution is to do what Steel Bank Common Lisp do and just release all code into he public domain.
