### ISSUE TITLE
Felixwebserver security issue?

### ISSUE THREAD

**Issue by rewolff** [felix-lang/felix#90]
Hi, 
I don't know where to report this.... 
I was searching for a typo in a file from my distribution. And google pointed me to 
  felix-lang.org/$//etc/.... 
Turns out, lots of files are accessible like that. This is usually not what you want.

**Comment by skaller** [comment]
> On 16 Nov 2016, at 20:41, rewolff <notifications@github.com> wrote:
> 
> Hi,
> I don't know where to report this....
> I was searching for a typo in a file from my distribution. And google pointed me to
> felix-lang.org/$//etc/....
> Turns out, lots of files are accessible like that. This is usually not what you want.

The webserver has the same privileges as a more or less ordinary user.
It’s designed as a programmers webserver to run on their local machine
as localhost. 

In particular it provides hyperlinks to C/C++ include files, so it can’t
restrict access to the usual webserver root.

It’s not a bug, its a design feature :-)

The server could be improved in many ways including security.


—
john skaller
skaller@users.sourceforge.net
http://felix-lang.org

**Comment by rewolff** [comment]
OK. if it's intentional. There is a typo in there somewhere. dhcient instead of dhclient....  (as distrbuted... :-) )
