### ISSUE TITLE
Update buildchain Ocaml on Windows to latest

### ISSUE THREAD

**Issue by gbluma** [felix-lang/felix#97]
It would be good to update Ocaml to the latest version. We can do this easily on Linux, but for Windows the compile requires a specialized configuration. If I remember correctly we have to do something to support dynamic linkage of natively compiled binaries.

**Comment by skaller** [comment]
> On 3 Sep. 2017, at 13:05, Garrett Bluma <notifications@github.com> wrote:
> 
> It would be good to update Ocaml to the latest version. We can do this easily on Linux, but for Windows the compile requires a specialized configuration. If I remember correctly we have to do something to support dynamic linkage of natively compiled binaries.

Maybe Shayne can help.

—
john skaller
skaller@users.sourceforge.net
http://felix-lang.org

**Comment by ahedgewitch** [comment]
This can probably be closed, right?

**Comment by skaller** [comment]
ok
